version: "3.9"

services:
  api:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    image: salary-manager:api
    volumes:
      - ./backend/api:/api/
    expose:
      - 80
    # command: uvicorn main:app --host 0.0.0.0 --reload
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`fastapi.localhost`)"
  traefik:
    image: traefik:v2.9.6
    ports:
      - 8008:80
      - 8081:8080
    volumes:
      - "./traefik/traefik.dev.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
