version = 0.1
[default.deploy.parameters]
stack_name = "salary-manager"
resolve_s3 = true
s3_prefix = "salary-manager"
region = "us-east-2"
profile = "my-own"
capabilities = "CAPABILITY_IAM"
image_repositories = []
