FROM tiangolo/uvicorn-gunicorn-fastapi:python3.11-slim

COPY requirements.txt .
RUN pip install -r requirements.txt

# ENV MODULE_NAME=api.main
# ENV APP_MODULE=api.main:app
WORKDIR /api

COPY ./api /api
