version: "3.9"
services:
    salary-manager-backend:
        build: ./backend
        volumes:
            - ./backend/django_project:/django_project
        ports:
            - 8000:8000
        image: salary-manager-backend:django_project
        command: python manage.py runserver 0:8000
        env_file:
            - envs/dev_django.env
            - envs/dev_postgres.env
        entrypoint: ["/entrypoint.sh"]
    salary-manager-db:
        image: postgres
        volumes: salary_manager_data:/var/lib/postgres/data
        env_file:
            - envs/dev_postgres.env
volumes:
    salary_manager_data: